"""Update transaction ItemNumber field length to 8

Revision ID: 1889a61e6871
Revises: 7690e7f602b7
Create Date: 2026-03-16 23:52:25.591464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1889a61e6871'
down_revision: Union[str, None] = '7690e7f602b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debtor',
    sa.Column('IPR', sa.String(length=26), nullable=False),
    sa.Column('SeqId', sa.Integer(), nullable=False),
    sa.Column('ClientNumber', sa.String(length=7), nullable=False),
    sa.Column('ClientAgreementNumber', sa.String(length=3), nullable=False),
    sa.Column('AgreementCurrency', sa.String(length=3), nullable=False),
    sa.Column('DebtorNumber', sa.String(length=10), nullable=False),
    sa.Column('AccountNumber', sa.String(length=3), nullable=False),
    sa.Column('AccountCurrency', sa.String(length=3), nullable=False),
    sa.Column('ClientName', sa.String(length=70), nullable=False),
    sa.Column('DebtorName', sa.String(length=70), nullable=False),
    sa.Column('DebtorAddr1', sa.String(length=40), nullable=True),
    sa.Column('DebtorAddr2', sa.String(length=40), nullable=True),
    sa.Column('DebtorAddr3', sa.String(length=40), nullable=True),
    sa.Column('DebtorCity', sa.String(length=40), nullable=True),
    sa.Column('DebtorPostCode', sa.String(length=12), nullable=True),
    sa.Column('DebtorCountry', sa.String(length=2), nullable=True),
    sa.Column('CreditController', sa.String(length=40), nullable=True),
    sa.Column('InpaymentBankCode', sa.String(length=8), nullable=True),
    sa.Column('InpaymentBankAccount', sa.String(length=8), nullable=True),
    sa.Column('InpaymentIbanNumber', sa.String(length=34), nullable=True),
    sa.Column('DebtorContact', sa.String(length=70), nullable=True),
    sa.Column('DebtorStmtEmail', sa.String(length=50), nullable=True),
    sa.Column('CallIsOptOut', sa.Boolean(), nullable=False),
    sa.Column('StmtFlag', sa.Boolean(), nullable=False),
    sa.Column('StmtRunDay', sa.String(length=2), nullable=True),
    sa.Column('DebtorFax', sa.String(length=20), nullable=True),
    sa.Column('CustomerAccountBalance', sa.Numeric(), nullable=True),
    sa.Column('ApplicationDate', sa.Date(), nullable=False),
    sa.Column('ExtractDate', sa.Date(), nullable=False),
    sa.Column('MigrationReference', sa.String(length=30), nullable=True),
    sa.Column('EndField', sa.String(length=1), nullable=True),
    sa.Column('RunId', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('IPR')
    )
    op.create_table('debtor_file_validation',
    sa.Column('ID', sa.UUID(), nullable=False),
    sa.Column('ValidationDateTime', sa.DateTime(), nullable=False),
    sa.Column('Error', sa.String(length=255), nullable=False),
    sa.Column('ConditionName', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('FileName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    op.create_table('debtor_record_validation',
    sa.Column('ID', sa.UUID(), nullable=False),
    sa.Column('RunId', sa.UUID(), nullable=False),
    sa.Column('IPR', sa.String(length=26), nullable=False),
    sa.Column('ValidationDateTime', sa.DateTime(), nullable=False),
    sa.Column('Error', sa.String(length=255), nullable=False),
    sa.Column('ConditionName', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('FileName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    op.create_table('file_validation_rule',
    sa.Column('ID', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    op.create_table('record_validation_rule',
    sa.Column('ID', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    op.create_table('run_batch',
    sa.Column('ID', sa.UUID(), nullable=False),
    sa.Column('DebtorFileName', sa.String(length=255), nullable=True),
    sa.Column('TransactionFileName', sa.String(length=255), nullable=True),
    sa.Column('HasDebtorFileValidated', sa.Boolean(), nullable=True),
    sa.Column('HasTransactionFileValidated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('run_control',
    sa.Column('ID', sa.UUID(), nullable=False),
    sa.Column('DebtorRunDateTime', sa.DateTime(), nullable=True),
    sa.Column('DebtorFileName', sa.String(length=255), nullable=True),
    sa.Column('TransactionFileName', sa.String(length=255), nullable=True),
    sa.Column('TransactionRunDateTime', sa.DateTime(), nullable=True),
    sa.Column('ApplicationDate', sa.Date(), nullable=True),
    sa.Column('ExtractDate', sa.Date(), nullable=True),
    sa.Column('ReceivedDate', sa.Date(), nullable=True),
    sa.Column('IsValidTransactionFile', sa.Boolean(), nullable=True),
    sa.Column('IsValidDebtorFile', sa.Boolean(), nullable=True),
    sa.Column('HasDebtorFileProcessed', sa.Boolean(), nullable=True),
    sa.Column('HasTransactionFileProcessed', sa.Boolean(), nullable=True),
    sa.Column('HasFileReceiptNotified', sa.Boolean(), nullable=True),
    sa.Column('HasFilesProcessedNotified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('statement',
    sa.Column('ID', sa.UUID(), nullable=False),
    sa.Column('StatementRequestId', sa.UUID(), nullable=True),
    sa.Column('IPR', sa.String(length=26), nullable=False),
    sa.Column('OpenTextIPR', sa.String(length=255), nullable=False),
    sa.Column('RunId', sa.UUID(), nullable=False),
    sa.Column('FileName', sa.String(length=255), nullable=False),
    sa.Column('StatementRequestDateTime', sa.DateTime(), nullable=False),
    sa.Column('OpenTextTrackerId', sa.Text(), nullable=True),
    sa.Column('RequestSubmissionStatus', sa.String(length=26), nullable=True),
    sa.Column('PdfGenerationStatus', sa.String(length=26), nullable=True),
    sa.Column('StatementRequestBody', sa.Text(), nullable=False),
    sa.Column('PdfContent', sa.Text(), nullable=True),
    sa.Column('StatementProcessingStatus', sa.Text(), nullable=True),
    sa.Column('ReasonForFailure', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('statement_request',
    sa.Column('StatementRequestID', sa.UUID(), nullable=False),
    sa.Column('StatementRequestDate', sa.Date(), nullable=False),
    sa.Column('ExpectedStatementCount', sa.Numeric(precision=10), nullable=False),
    sa.Column('SubmissionStatus', sa.String(length=26), nullable=True),
    sa.Column('SubmissionResult', sa.Text(), nullable=True),
    sa.Column('StatementBase64RequestBody', sa.Text(), nullable=True),
    sa.Column('SubmissionId', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('StatementRequestID')
    )
    op.create_table('statement_validation',
    sa.Column('ID', sa.UUID(), nullable=False),
    sa.Column('IPR', sa.String(length=26), nullable=False),
    sa.Column('ConditionName', sa.String(length=255), nullable=False),
    sa.Column('Log', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('RunId', sa.UUID(), nullable=False),
    sa.Column('FileName', sa.String(length=255), nullable=False),
    sa.Column('StatementRequestDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('transaction',
    sa.Column('RunId', sa.UUID(), nullable=False),
    sa.Column('IPR', sa.String(length=26), nullable=False),
    sa.Column('TransactionId', sa.UUID(), nullable=False),
    sa.Column('SeqId', sa.Integer(), nullable=False),
    sa.Column('ClientNumber', sa.String(length=7), nullable=False),
    sa.Column('ClientAgreementNumber', sa.String(length=3), nullable=False),
    sa.Column('AgreementCurrency', sa.String(length=3), nullable=False),
    sa.Column('AccountCurrency', sa.String(length=3), nullable=False),
    sa.Column('DebtorNumber', sa.String(length=10), nullable=False),
    sa.Column('AccountNumber', sa.String(length=3), nullable=False),
    sa.Column('ItemNumber', sa.String(length=8), nullable=False),
    sa.Column('DocumentDate', sa.Date(), nullable=False),
    sa.Column('TransactionType', sa.String(length=20), nullable=False),
    sa.Column('DocumentReference', sa.String(length=15), nullable=False),
    sa.Column('OrderReference', sa.String(length=15), nullable=False),
    sa.Column('DueDate', sa.Date(), nullable=True),
    sa.Column('Disputed', sa.Boolean(), nullable=False),
    sa.Column('Overdue', sa.Boolean(), nullable=False),
    sa.Column('ItemBalance', sa.Numeric(), nullable=False),
    sa.Column('ApplicationDate', sa.Date(), nullable=False),
    sa.Column('ExtractDate', sa.Date(), nullable=False),
    sa.Column('MigrationReference', sa.String(length=30), nullable=False),
    sa.Column('EndField', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('TransactionId')
    )
    op.create_table('transaction_file_validation',
    sa.Column('ID', sa.UUID(), nullable=False),
    sa.Column('ValidationDateTime', sa.DateTime(), nullable=False),
    sa.Column('Error', sa.String(length=255), nullable=False),
    sa.Column('ConditionName', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('FileName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    op.create_table('transaction_record_validation',
    sa.Column('ID', sa.UUID(), nullable=False),
    sa.Column('RunId', sa.UUID(), nullable=False),
    sa.Column('IPR', sa.String(length=26), nullable=False),
    sa.Column('ValidationDateTime', sa.DateTime(), nullable=False),
    sa.Column('Error', sa.String(length=255), nullable=False),
    sa.Column('ConditionName', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('FileName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_record_validation')
    op.drop_table('transaction_file_validation')
    op.drop_table('transaction')
    op.drop_table('statement_validation')
    op.drop_table('statement_request')
    op.drop_table('statement')
    op.drop_table('run_control')
    op.drop_table('run_batch')
    op.drop_table('record_validation_rule')
    op.drop_table('file_validation_rule')
    op.drop_table('debtor_record_validation')
    op.drop_table('debtor_file_validation')
    op.drop_table('debtor')
    # ### end Alembic commands ###
