"""update transaction model

Revision ID: 7690e7f602b7
Revises: 6df0cac542d8
Create Date: 2026-03-16 17:39:41.758781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7690e7f602b7'
down_revision: Union[str, None] = '6df0cac542d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'debtor_file_validation', ['ID'])
    op.create_unique_constraint(None, 'debtor_record_validation', ['ID'])
    op.create_unique_constraint(None, 'file_validation_rule', ['ID'])
    op.create_unique_constraint(None, 'record_validation_rule', ['ID'])
    op.alter_column('transaction', 'RunId',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('transaction', 'AgreementCurrency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('transaction', 'AccountCurrency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('transaction', 'AccountNumber',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('transaction', 'ItemNumber',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=7),
               nullable=False)
    op.alter_column('transaction', 'DocumentDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('transaction', 'TransactionType',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('transaction', 'DocumentReference',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               nullable=False)
    op.alter_column('transaction', 'OrderReference',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               nullable=False)
    op.alter_column('transaction', 'ItemBalance',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('transaction', 'ApplicationDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('transaction', 'ExtractDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('transaction', 'MigrationReference',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('transaction', 'EndField',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.drop_index(op.f('ix_transaction_IPR'), table_name='transaction')
    op.create_unique_constraint(None, 'transaction_file_validation', ['ID'])
    op.create_unique_constraint(None, 'transaction_record_validation', ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_record_validation', type_='unique')
    op.drop_constraint(None, 'transaction_file_validation', type_='unique')
    op.create_index(op.f('ix_transaction_IPR'), 'transaction', ['IPR'], unique=False)
    op.alter_column('transaction', 'EndField',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.alter_column('transaction', 'MigrationReference',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('transaction', 'ExtractDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('transaction', 'ApplicationDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('transaction', 'ItemBalance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('transaction', 'OrderReference',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('transaction', 'DocumentReference',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('transaction', 'TransactionType',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('transaction', 'DocumentDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('transaction', 'ItemNumber',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('transaction', 'AccountNumber',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('transaction', 'AccountCurrency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('transaction', 'AgreementCurrency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('transaction', 'RunId',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'record_validation_rule', type_='unique')
    op.drop_constraint(None, 'file_validation_rule', type_='unique')
    op.drop_constraint(None, 'debtor_record_validation', type_='unique')
    op.drop_constraint(None, 'debtor_file_validation', type_='unique')
    # ### end Alembic commands ###
