"""add assignment letter tables

Revision ID: 92cb59edfa00
Revises: ac91104beace
Create Date: 2026-03-17 16:54:42.768140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92cb59edfa00'
down_revision: Union[str, None] = 'ac91104beace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_letter',
    sa.Column('ID', sa.UUID(), nullable=False),
    sa.Column('AssignmentLetterRequestId', sa.UUID(), nullable=True),
    sa.Column('IPR', sa.String(length=26), nullable=False),
    sa.Column('OpenTextIPR', sa.String(length=255), nullable=False),
    sa.Column('RunId', sa.UUID(), nullable=False),
    sa.Column('FileName', sa.String(length=255), nullable=False),
    sa.Column('RequestDateTime', sa.DateTime(), nullable=False),
    sa.Column('OpenTextTrackerId', sa.Text(), nullable=True),
    sa.Column('RequestSubmissionStatus', sa.String(length=26), nullable=True),
    sa.Column('PdfGenerationStatus', sa.String(length=26), nullable=True),
    sa.Column('RequestBody', sa.Text(), nullable=True),
    sa.Column('PdfContent', sa.Text(), nullable=True),
    sa.Column('ProcessingStatus', sa.Text(), nullable=True),
    sa.Column('ReasonForFailure', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('assignment_letter_request',
    sa.Column('AssignmentLetterRequestID', sa.UUID(), nullable=False),
    sa.Column('RequestDate', sa.Date(), nullable=False),
    sa.Column('ExpectedLetterCount', sa.Numeric(precision=10), nullable=False),
    sa.Column('SubmissionStatus', sa.String(length=26), nullable=True),
    sa.Column('SubmissionResult', sa.Text(), nullable=True),
    sa.Column('RequestBase64Body', sa.Text(), nullable=True),
    sa.Column('SubmissionId', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('AssignmentLetterRequestID')
    )
    op.create_table('assignment_letter_validation',
    sa.Column('ID', sa.UUID(), nullable=False),
    sa.Column('IPR', sa.String(length=26), nullable=False),
    sa.Column('ConditionName', sa.String(length=255), nullable=False),
    sa.Column('Log', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('RunId', sa.UUID(), nullable=False),
    sa.Column('FileName', sa.String(length=255), nullable=False),
    sa.Column('ValidationDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_letter_validation')
    op.drop_table('assignment_letter_request')
    op.drop_table('assignment_letter')
    # ### end Alembic commands ###
