"""update debtor table

Revision ID: 9fa9297a7f30
Revises: 1889a61e6871
Create Date: 2026-03-17 14:00:23.525701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa9297a7f30'
down_revision: Union[str, None] = '1889a61e6871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debtor', sa.Column('BankName', sa.String(length=70), nullable=True))
    op.add_column('debtor', sa.Column('BankAddress1', sa.String(length=50), nullable=True))
    op.add_column('debtor', sa.Column('BankAddress2', sa.String(length=40), nullable=True))
    op.add_column('debtor', sa.Column('BankAddress3', sa.String(length=40), nullable=True))
    op.add_column('debtor', sa.Column('BankCity', sa.String(length=40), nullable=True))
    op.add_column('debtor', sa.Column('BankState', sa.String(length=40), nullable=True))
    op.add_column('debtor', sa.Column('BankPostcode', sa.String(length=12), nullable=True))
    op.add_column('debtor', sa.Column('AssignmentDue', sa.Boolean(), nullable=True))
    op.execute('UPDATE debtor SET "AssignmentDue" = false WHERE "AssignmentDue" IS NULL')
    op.alter_column('debtor', 'AssignmentDue', existing_type=sa.Boolean(), nullable=False)
    op.add_column('debtor', sa.Column('DunningReminder', sa.String(length=1), nullable=True))
    op.add_column('debtor', sa.Column('DunningCycleCode', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debtor', 'DunningCycleCode')
    op.drop_column('debtor', 'DunningReminder')
    op.drop_column('debtor', 'AssignmentDue')
    op.drop_column('debtor', 'BankPostcode')
    op.drop_column('debtor', 'BankState')
    op.drop_column('debtor', 'BankCity')
    op.drop_column('debtor', 'BankAddress3')
    op.drop_column('debtor', 'BankAddress2')
    op.drop_column('debtor', 'BankAddress1')
    op.drop_column('debtor', 'BankName')
    # ### end Alembic commands ###
