"""update transaction add item amount

Revision ID: ac91104beace
Revises: 9fa9297a7f30
Create Date: 2026-03-17 15:40:02.385667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac91104beace'
down_revision: Union[str, None] = '9fa9297a7f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('ItemAmount', sa.Numeric(), nullable=True))
    op.execute('UPDATE "transaction" SET "ItemAmount" = "ItemBalance" WHERE "ItemAmount" IS NULL')
    op.alter_column('transaction', 'ItemAmount', existing_type=sa.Numeric(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'ItemAmount')
    # ### end Alembic commands ###
